version: "3"

services:
  db:
    image: mysql:8
    container_name: f1manager_db
    env_file: .env.dev
    environment:
      MYSQL_DATABASE: ${DB_NAME:-F1Manager_dev}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-mysql}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-mysql}
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"         
volumes:
  my-db:
